export const WorkShiftModel = {
    HolidayCoefficent: null,
    LunchCoefficent: null,
    NoEndHourPunishDay: null,
    NoEndHourPunishHour: null,
    NoStartHourPunishDay: null,
    NoStartHourPunishHour: null,
    NormalDayCoefficent: null,
    NotWorkEnoughCoefficent: null,
    OffDayCoefficent: null,
    WorkShiftAllowEndSoon: null,
    WorkShiftAllowLate: null,
    WorkShiftBreakEnd: null,
    WorkShiftBreakFrom: null,
    WorkShiftBreakStart: null,
    WorkShiftBreakTo: null,
    WorkShiftCode: null,
    WorkShiftEnd: null,
    WorkShiftEndFrom: null,
    WorkShiftEndTo: null,
    WorkShiftId: "00000000-0000-0000-0000-000000000000",
    WorkShiftLatePunishId: null,
    WorkShiftName: null,
    WorkShiftStart: null,
    WorkShiftStartFrom: null,
    WorkShiftStartTo: null,
    WorkShiftWorkingDay: null,
    WorkShiftWorkingHour: null, 
    CreatedTime: new Date(),
    IsHavingBreakout: false,
    IsHavingBreakoutCheckInOut: false,
    IsHavingCheckinDetail: false,
    IsHavingCheckoutDetail: false,
    IsHavingLateOrSoonAllow: false,
    IsHavingLateOrSoonPunish: false,
    NoEndTime: false,
    NoStartTime: false,
}